# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a2404035d5427d1b9d85aa6ccc06e72269343270cc078ced4e119a130cf07cec66299c180704f517ead32bf1971fd5e34ec81564d3d508e9c7324527b284d86

test:
  secret_key_base: 676a37f20a675809210624b97eacc78f57c1b14582917368d9e2629d1fef42bfed0d5c2b10aff21c48a116412f5d06192614681ab165140baf580eda9b58922f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
